 <div class="span12 center clearfix push">
        <div class="row">    
           <div class="span6">
                <h1>Mission</h1>
                <p>	Make a opensource RIA in Zend Framework using ten open datasets. Find links between these datasets and display them in a creative way. This mission was completed in name of <br/><a href="http://www.arteveldehs.be" title="Artevelde University College Ghent website">Artevelde University College Ghent</a>.<br/>
                    &copy; 2012-2013
                </p>
            </div>
            <div  class="span6">
                    <h1>Technology</h1><br/>
                    <ul>
                    <li>PHP</li>
                    <li>Zend Framework</li>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>JS & Jquery</li>
                    <li>Codeinchaos RESTful API</li>  
                    </ul>
                </div>
		 </div>
         <div class="row">  
       	    <div  class="span6">
                    <h1>Result</h1><br/>
                    A simple small app that shows you all kinds of activities in Ghent.
            </div>
                <div class="span6">
                <div class="row">
                    <div class="span2 footer-img">
                        <a href="http://www.twitter.com/DeWulfJens" title="DeWulfJens on Twitter"><img src="<?php echo $this->baseUrl('_assets/img/me.png') ?>" class="img-polaroid profile-pic" /></a>
                    </div>
                    <h1>Who am I</h1>
                    <p>
                        <a href="http://www.twitter.com/DeWulfJens" title="DeWulfJens on Twitter">@DeWulfJens</a><br/>
                        Jens De Wulf<br/>
                        <em>"I love designing, coding, tweaking for front end."</em>
                    </p>
                </div>
            </div>
 