<?php 
    $this->inlineScript()
         ->appendFile($this->baseUrl('_scripts/js/funspots.js')) 
    ;
?>

<div class="span12 center clearfix push" id='answers-title'>
    <div class="row">
        <div class="span12">
            <h1>This is where the fun starts</h1>
            <p class="lead lead-push">
                Pick an activity or go random and watch the fun appear.<br/>
            </p>
            <button class="btn pillBtn" onclick='random();' title='Random Activity'>RANDOM</button>
            <select id="activity" name="activity" onchange="loadMarkers()">			
                                <option value=""></option>
            </select>
            <?php echo ?>
        </div>
    </div>
</div>
<div class="span12 center clearfix" id='map_span'>
    <div id="gmap"></div>
</div>
<script>
var _baseUrl = "<?php echo WEB_BASE_PATH; ?>";
</script>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=false"></script>
