<?php
    $loggedin = false;
    $auth = Zend_Auth::getInstance();
    $id = $auth->getStorage()->read()['id'];
    $userMapper = new Application_Model_UserMapper();
    try {   
        if($user = new Application_Model_User($userMapper->read($id)))
        {
            $loggedin = true;
            $username = $user->getUsername();
        }
    }
    catch (Exception $e)
    {
        $loggedin = false;;
    }
?>
<div class="span12 center clearfix push">
    <div class="row">
        <div class="span12">
            <h1>Bored ?</h1>
            <p class="lead lead-push">
                Are you in Ghent?<br/>
                 <?php if($loggedin): ?>
					Then find some fun right now! </p><a class="left pillBtn" title="Find Fun" href="<?php echo $this->url(array('controller'=>'user', 'action' => 'fun'),'default',true) ?>">Find Fun</a>
                    <?php else: ?>
                    Then register or login and find fun things to do!</p>
                    <a class="left pillBtn" title="Register" href="<?php echo $this->url(array('controller'=>'account', 'action' => 'register'),'default',true) ?>">Register</a><a class="left pillBtn" title="Register" href="<?php echo $this->url(array('controller'=>'account', 'action' => 'login'),'default',true) ?>">Login</a>
                    <?php endif; ?> 
        </div>
    </div>
</div>
