<div class="span12 center clearfix push">
    <div class="row">
        <div class="span6">
            <h1 class="">Retrieve password</h1>
            <?php echo $this->form ?>
                

                <?php 
                    if(isset($this->error)) {
                        echo "<p>" . $this->error . "</p>";
                    }
                ?>
            </form>
        </div>
    </div>
</div>