<div class="span12 center clearfix push">
        <h1>Server Error</h1>
        <h2><?php echo $this->message ?></h2>

        <?php if (isset($this->exception)): ?>

        <h3>Information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?>
            </pre>
    
            <h3>Request Parameters:</h3>
            <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
            </pre>
        </p>

        

        <?php endif ?>
</div>