<?php 
    $this->inlineScript()
    ;
?>
<div class="span12 center clearfix push">
    <div class="row">
        <div class="span6">
            <h1>Welcome <?php echo $this->firstname ?> <?php echo $this->surname ?></h1>
            <strong>Email</strong><br/>
            <p><?php echo $this->email ?></p>
            <strong>Gender</strong><br/>
            <p><?php echo ($this->gender == "m"?"Man":"Woman") ?></p>
            <strong>Joined</strong><br/>
            <p><?php echo $this->createddate ?></p>
            <strong>Last time you logged in</strong><br/>
            <p><?php echo $this->lastloggedindate ?></p>
            <a href="<?php echo $this->url(
                array('controller'=>'user', 'action' => 'edit'),
                'default',
                true) ?>" class="pillBtn">Edit Profile</a>
        </div>
        <div class="span6 profile-image">
            <img src="<?php 
            if ($this->picture == null) {
                echo WEB_BASE_PATH . "_assets/img/standard_profilePic.png";
            }
            else {
                echo WEB_BASE_PATH . "images/" . $this->picture;
            } 
            ?>" class="img-polaroid profile-pic" alt="picture-<?php echo $this->username ?>" />
        </div>
    </div>
</div>
<script>
var _baseUrl = "<?php echo WEB_BASE_PATH; ?>";
</script>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=false"></script>